#!/usr/bin/env bash
# =============================================================================
# Greenplum 主机操作系统参数一键配置脚本（RHEL/CentOS 7.x）
#
# 对应《风哥就业培训班 - 03.os级别txt脚本.txt》，把其中需要手工逐段执行的：
#   01 内核参数(sysctl)  02 资源限制(limits/pam)  03 安全(SELinux/防火墙/运行级别)
#   XFS 挂载优化 / 磁盘预读 / IO 调度器 / GRUB(关闭NUMA与THP) / RemoveIPC
#   本地光盘 yum 源 / 安装依赖包
# 全部串成一个可重复执行（幂等）、带日志、带结果汇总的脚本。
#
# 用法（每台节点 root 执行）：
#   bash greenplum_os_setup.sh            # 按默认/可选 conf 一键执行
#   FORMAT_DISK=yes bash greenplum_os_setup.sh   # 确认数据盘可清空时，允许自动建 XFS
#   REBOOT=yes bash greenplum_os_setup.sh        # 末尾自动重启（默认只提示不重启）
#
# 可选：把要改的变量放到同目录 greenplum_os.conf（无需改动本脚本），存在则自动加载。
#
# 相对原始 txt 做的【安全化/幂等】处理（参数值与原版完全一致）：
#   * sysctl 不再反复 append 到 /etc/sysctl.conf，改写独立文件
#     /etc/sysctl.d/99-greenplum.conf，重复执行不会产生重复行；
#   * 资源限制写 /etc/security/limits.d/99-greenplum.conf，
#     【不执行】原版的 rm -f /etc/security/limits.d/*（避免误删其它软件限制）；
#   * pam_limits.so、fstab、rc.local、grub、yum repo 均做“已存在则跳过”，可重复执行；
#   * 数据盘默认【不自动格式化】（防误删数据），需显式 FORMAT_DISK=yes；
#     检测不到块设备时自动降级为系统盘目录并告警，不阻断其它配置；
#   * 末尾默认【不自动重启】（避免中断远程批量部署），REBOOT=yes 才重启；
#   * 光盘 yum 源挂载失败、个别包(如 EL7 的 e4fsprogs)缺失只告警，不中断整体。
#
# 统一目录：默认数据盘挂载到 /data/greenplum（原版为 /greenplum、/usr/local）。
# 退出码：0 成功（可能含告警）；非 0 存在致命失败项，见结尾汇总与日志。
# =============================================================================
set -u
umask 022

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FILE="${LOG_FILE:-/var/log/greenplum_os_setup.log}"

# ----------------------------- 可配置项（默认值） ----------------------------
# 数据块设备（不含分区号）与其分区
BLOCK_DEV="${BLOCK_DEV:-sdb}"
DATA_PART="${DATA_PART:-/dev/${BLOCK_DEV}1}"
# 数据盘挂载点（统一目录）；原版 /greenplum，本体系统一为 /data/greenplum
GP_MOUNT="${GP_MOUNT:-/data/greenplum}"
XFS_OPTS="${XFS_OPTS:-rw,noatime,inode64,allocsize=16m}"
# 是否额外把 /dev/sdb2 挂到 /usr/local（原版有；软件已统一到 /data/greenplum，默认关）
MOUNT_LOCAL="${MOUNT_LOCAL:-no}"
LOCAL_PART="${LOCAL_PART:-/dev/${BLOCK_DEV}2}"
LOCAL_MOUNT="${LOCAL_MOUNT:-/usr/local}"
# 磁盘预读扇区数
READAHEAD="${READAHEAD:-65536}"
# 是否更新 GRUB（numa=off transparent_hugepage=never elevator=deadline），重启后生效
UPDATE_GRUB="${UPDATE_GRUB:-yes}"
# 本地光盘 yum 源：dvd=配置 file:///mnt/linux 源；none=不动 yum 源直接用现有源装包
YUM_REPO="${YUM_REPO:-dvd}"
ISO_DEV="${ISO_DEV:-/dev/cdrom}"
ISO_MOUNT="${ISO_MOUNT:-/mnt/linux}"
# 危险/中断性开关（默认安全）
FORMAT_DISK="${FORMAT_DISK:-no}"
REBOOT="${REBOOT:-no}"

# 同目录可选 conf 覆盖（不存在则忽略）
[ -f "$SCRIPT_DIR/greenplum_os.conf" ] && . "$SCRIPT_DIR/greenplum_os.conf"

# 依赖包（与原版 txt 完全一致）
GP_PACKAGES=(openssh-clients gcc gcc-c++ make automake autoconf libtool krb5-devel perl
  rsync coreutils glib2 ed lrzsz sysstat e4fsprogs xfsprogs ntp readline-devel zlib
  zlib-devel unzip)

# ------------------------------- 日志与结果汇总 -------------------------------
if [ -t 1 ]; then C_RED=$'\e[31m'; C_GRN=$'\e[32m'; C_YEL=$'\e[33m'; C_BLU=$'\e[36m'; C_RST=$'\e[0m'
else C_RED=''; C_GRN=''; C_YEL=''; C_BLU=''; C_RST=''; fi
FAILED=()
_log(){ printf '%s %s\n' "[$(date '+%F %T')]" "$*"; }
log(){ _log "${C_BLU}==>>${C_RST} $*"; }
ok (){ _log "${C_GRN}[ OK ]${C_RST} $*"; }
warn(){ _log "${C_YEL}[WARN]${C_RST} $*"; }
err(){ _log "${C_RED}[FAIL]${C_RST} $*"; FAILED+=("$*"); }
step(){ printf '\n%s\n' "------------------------------------------------"; _log "${C_BLU}### $*${C_RST}"; }

# 命令存在性
have(){ command -v "$1" >/dev/null 2>&1; }
# 设备存在：/dev/xxx 或 /sys/block 下有同名盘
dev_exists(){ [ -b "$1" ] || [ -d "/sys/block/${1#/dev/}" ]; }

# =============================================================================
# 00. 前置检查
# =============================================================================
preflight() {
  step "00 前置检查"
  if [ "$(id -u)" -ne 0 ]; then echo "请使用 root 执行本脚本"; exit 1; fi
  ok "当前为 root 用户"
  if [ -r /etc/redhat-release ]; then ok "操作系统：$(cat /etc/redhat-release)"; else warn "未识别到 RedHat/CentOS 发行版，继续尝试"; fi
  mkdir -p "$(dirname "$LOG_FILE")" 2>/dev/null || true
}

# =============================================================================
# 01. 内核参数（独立 drop-in，幂等）
# =============================================================================
setup_sysctl() {
  step "01 配置内核参数 sysctl"
  local f=/etc/sysctl.d/99-greenplum.conf
  cat > "$f" <<'EOF'
# ---- Greenplum OS tuning (generated by greenplum_os_setup.sh) ----
fs.aio-max-nr = 1048576
fs.file-max = 6815744
net.ipv4.ip_local_port_range = 9000 65500
net.ipv4.conf.default.accept_source_route = 0
net.ipv4.tcp_max_syn_backlog = 4096
net.ipv4.conf.all.arp_filter = 1
net.core.rmem_default = 262144
net.core.rmem_max = 4194304
net.core.wmem_default = 262144
net.core.wmem_max = 1048586
kernel.sem = 4096 2147483647 2147483646 512000
kernel.shmmax = 1073741824
kernel.shmall = 262144
kernel.shmmni = 4096
kernel.sysrq = 1
kernel.core_uses_pid = 1
kernel.msgmnb = 65536
kernel.msgmax = 65536
kernel.msgmni = 2048
vm.swappiness = 10
vm.overcommit_memory = 2
vm.overcommit_ratio = 95
vm.zone_reclaim_mode = 0
vm.dirty_expire_centisecs = 500
vm.dirty_writeback_centisecs = 100
# 内存 <=64G 使用 ratio 方案（原版默认）；>64G 可改用 dirty_background_bytes/dirty_bytes
vm.dirty_background_ratio = 3
vm.dirty_ratio = 10
EOF
  if sysctl -p "$f" >/dev/null 2>&1; then ok "内核参数已写入 $f 并生效（sysctl -p）"
  else err "sysctl -p $f 存在无法生效的参数，请检查"; fi
}

# =============================================================================
# 02. 资源限制 + pam_limits（幂等；不删除 limits.d 下其它文件）
# =============================================================================
setup_limits() {
  step "02 配置资源限制 limits 与 pam_limits"
  local f=/etc/security/limits.d/99-greenplum.conf
  cat > "$f" <<'EOF'
# ---- Greenplum resource limits (generated) ----
*  soft  nproc   unlimited
*  hard  nproc   unlimited
*  soft  nofile  524288
*  hard  nofile  524288
*  soft  stack   unlimited
*  hard  stack   unlimited
*  soft  memlock unlimited
*  hard  memlock unlimited
EOF
  ok "资源限制已写入 $f（未删除 limits.d 下其它文件）"

  local pam=/etc/pam.d/login
  if grep -qE '^\s*session\s+required\s+pam_limits\.so' "$pam" 2>/dev/null; then
    ok "$pam 已包含 pam_limits.so，跳过"
  else
    echo "session    required     pam_limits.so" >> "$pam"
    ok "已向 $pam 追加 pam_limits.so"
  fi
}

# =============================================================================
# 03. 安全配置：SELinux / 防火墙 / 运行级别
# =============================================================================
setup_security() {
  step "03 安全配置（SELinux / firewalld / 运行级别）"
  local se=/etc/selinux/config
  [ -f "$se" ] || se=/etc/sysconfig/selinux
  if [ -f "$se" ]; then
    sed -i 's/^\s*SELINUX=.*/SELINUX=disabled/' "$se"
    grep -q '^SELINUX=disabled' "$se" || echo 'SELINUX=disabled' >> "$se"
    ok "SELINUX 已设置为 disabled（配置文件）"
  else warn "未找到 SELinux 配置文件，跳过"; fi
  setenforce 0 >/dev/null 2>&1 && ok "当前 SELinux 已临时 setenforce 0" || ok "SELinux 当前非 enforcing 或已关闭"

  if have systemctl; then
    if systemctl list-unit-files 2>/dev/null | grep -q '^firewalld\.service'; then
      systemctl stop firewalld.service 2>/dev/null || true
      systemctl disable firewalld.service >/dev/null 2>&1 || true
      ok "firewalld 已停止并禁用"
    else ok "未安装 firewalld，跳过"; fi
    systemctl set-default multi-user.target >/dev/null 2>&1 && ok "默认运行级别已设为 multi-user.target" || warn "设置默认运行级别失败"
  else warn "无 systemctl，跳过防火墙/运行级别设置"; fi
}

# =============================================================================
# 04. XFS 数据盘：分区格式化(可选) + 挂载 + fstab（幂等，设备缺失自动降级）
# =============================================================================
mount_xfs() {  # $1=分区设备 $2=挂载点
  local part="$1" mp="$2"
  if mountpoint -q "$mp"; then ok "$mp 已挂载，跳过"; return 0; fi
  if [ ! -b "$part" ]; then warn "分区 $part 不存在，跳过其挂载"; return 1; fi
  mkdir -p "$mp"
  # 是否已有文件系统
  local fstype
  fstype="$(blkid -o value -s TYPE "$part" 2>/dev/null || true)"
  if [ -z "$fstype" ]; then
    if [ "$FORMAT_DISK" = "yes" ]; then
      log "在 $part 上创建 XFS 文件系统（FORMAT_DISK=yes）"
      mkfs.xfs -f "$part" >/dev/null 2>&1 && ok "$part 已格式化为 XFS" || { err "mkfs.xfs $part 失败"; return 1; }
    else
      warn "$part 无文件系统且未开启 FORMAT_DISK=yes，跳过（不会自动格式化以防误删数据）"
      return 1
    fi
  elif [ "$fstype" != "xfs" ]; then
    warn "$part 现有文件系统为 $fstype（非 xfs），不覆盖，跳过"
    return 1
  fi
  # fstab 幂等
  local uuid
  uuid="$(blkid -o value -s UUID "$part" 2>/dev/null || true)"
  if grep -qE "[[:space:]]${mp}[[:space:]]" /etc/fstab; then
    ok "/etc/fstab 已存在 $mp 挂载项，跳过写入"
  else
    if [ -n "$uuid" ]; then
      echo "UUID=$uuid $mp xfs $XFS_OPTS 0 0" >> /etc/fstab
    else
      echo "$part $mp xfs $XFS_OPTS 0 0" >> /etc/fstab
    fi
    ok "已写入 /etc/fstab：$mp ($XFS_OPTS)"
  fi
  mount "$mp" >/dev/null 2>&1 && ok "$mp 已挂载" || mount "$part" "$mp" >/dev/null 2>&1 && ok "$mp 已挂载" || { err "挂载 $mp 失败"; return 1; }
}

setup_disk() {
  step "04 XFS 数据盘 / 挂载优化"
  if dev_exists "/dev/$BLOCK_DEV"; then
    ok "检测到块设备 /dev/$BLOCK_DEV"
    mount_xfs "$DATA_PART" "$GP_MOUNT" || warn "数据盘挂载未完成，$GP_MOUNT 将使用系统盘目录（不阻断部署）"
    mkdir -p "$GP_MOUNT"
    if [ "$MOUNT_LOCAL" = "yes" ]; then mount_xfs "$LOCAL_PART" "$LOCAL_MOUNT" || warn "$LOCAL_MOUNT 挂载跳过"; fi
  else
    warn "未检测到 /dev/$BLOCK_DEV，跳过 XFS 挂载；创建目录 $GP_MOUNT（系统盘）"
    mkdir -p "$GP_MOUNT"
  fi
}

# =============================================================================
# 05. 磁盘预读(readahead) + rc.local（幂等）
# =============================================================================
setup_readahead() {
  step "05 磁盘预读 blockdev --setra $READAHEAD"
  local rc=/etc/rc.d/rc.local devs=("/dev/$BLOCK_DEV" "/dev/${BLOCK_DEV}1")
  [ "$MOUNT_LOCAL" = "yes" ] && devs+=("/dev/${BLOCK_DEV}2")
  touch "$rc"
  for d in "${devs[@]}"; do
    if [ -b "$d" ]; then
      blockdev --setra "$READAHEAD" "$d" >/dev/null 2>&1 && ok "$d 预读已设为 $READAHEAD" || warn "$d 设置预读失败"
      grep -qE "blockdev --setra $READAHEAD $d([[:space:]]|$)" "$rc" || echo "blockdev --setra $READAHEAD $d" >> "$rc"
    fi
  done
  chmod +x "$rc"
  if have systemctl && systemctl list-unit-files 2>/dev/null | grep -q '^rc-local\.service'; then
    systemctl enable rc-local.service >/dev/null 2>&1 || true
  fi
  ok "预读规则已写入 $rc（幂等）并赋予可执行权限"
}

# =============================================================================
# 06. IO 调度器 deadline（立即生效）
# =============================================================================
setup_scheduler() {
  step "06 IO 调度器 deadline"
  local s="/sys/block/$BLOCK_DEV/queue/scheduler"
  if [ -f "$s" ]; then
    echo deadline > "$s" 2>/dev/null && ok "$BLOCK_DEV 当前调度器：$(cat "$s")" \
      || warn "设置 deadline 失败（该内核可能为 mq-deadline/none，可由 GRUB elevator 参数兜底）"
  else warn "无 $s（设备不存在或无可调调度器），跳过"; fi
}

# =============================================================================
# 07. GRUB：numa=off transparent_hugepage=never elevator=deadline（幂等+备份）
# =============================================================================
setup_grub() {
  step "07 GRUB 关闭 NUMA / 透明大页 / 指定 deadline"
  # 立即关闭透明大页（重启前的当前内核也尽量生效）
  for thp in /sys/kernel/mm/transparent_hugepage/enabled /sys/kernel/mm/redhat_transparent_hugepage/enabled; do
    [ -f "$thp" ] && { echo never > "$thp" 2>/dev/null && ok "已即时关闭 THP：$thp" || true; }
  done
  if [ "$UPDATE_GRUB" != "yes" ]; then warn "UPDATE_GRUB!=yes，跳过 GRUB 修改"; return 0; fi
  local g=/etc/default/grub
  [ -f "$g" ] || { warn "未找到 $g，跳过"; return 0; }
  cp -a "$g" "$g.bak.$(date +%Y%m%d%H%M%S)"
  local need=("numa=off" "transparent_hugepage=never" "elevator=deadline") p cur
  cur="$(grep -E '^GRUB_CMDLINE_LINUX=' "$g")"
  for p in "${need[@]}"; do
    case " $cur " in
      *"$p"*) ;;  # 该参数已存在，跳过
      *) sed -i "s/\(GRUB_CMDLINE_LINUX=\"[^\"]*\)\"/\1 ${p}\"/" "$g" ;;
    esac
  done
  ok "已在 GRUB_CMDLINE_LINUX 注入：${need[*]}"
  if [ -d /sys/firmware/efi ] && [ -f /etc/grub2-efi.cfg ]; then
    grub2-mkconfig -o /etc/grub2-efi.cfg >/dev/null 2>&1 && ok "已重新生成 EFI grub2-efi.cfg" || err "grub2-mkconfig(efi) 失败"
  else
    grub2-mkconfig -o /etc/grub2.cfg >/dev/null 2>&1 && ok "已重新生成 /etc/grub2.cfg" || err "grub2-mkconfig 失败"
  fi
}

# =============================================================================
# 08. RemoveIPC=no
# =============================================================================
setup_removeipc() {
  step "08 logind RemoveIPC=no"
  local f=/etc/systemd/logind.conf
  if [ -f "$f" ]; then
    if grep -qE '^\s*RemoveIPC=no' "$f"; then ok "RemoveIPC=no 已存在，跳过"; else
      sed -i 's/^\s*#\?\s*RemoveIPC=.*/RemoveIPC=no/' "$f"
      grep -qE '^\s*RemoveIPC=no' "$f" || echo 'RemoveIPC=no' >> "$f"
      ok "已设置 RemoveIPC=no"
    fi
    have systemctl && systemctl restart systemd-logind >/dev/null 2>&1 && ok "systemd-logind 已重启" || warn "systemd-logind 重启跳过/失败"
  else warn "无 $f，跳过"; fi
}

# =============================================================================
# 09. 本地光盘 yum 源 + 依赖包
# =============================================================================
setup_yum() {
  step "09 yum 源与依赖包安装"
  local repod=/etc/yum.repos.d repo=itpux.repo
  if [ "$YUM_REPO" = "dvd" ]; then
    mkdir -p "$ISO_MOUNT"
    if mountpoint -q "$ISO_MOUNT"; then ok "光盘已挂载于 $ISO_MOUNT，跳过"; else
      mount "$ISO_DEV" "$ISO_MOUNT" >/dev/null 2>&1 && ok "已挂载 $ISO_DEV -> $ISO_MOUNT" \
        || warn "光盘挂载失败（$ISO_DEV），将尝试使用系统现有 yum 源"
    fi
    if mountpoint -q "$ISO_MOUNT"; then
      mkdir -p "$repod/bk"
      # 仅移动“非本脚本生成”的 repo，且用 mv -n 防覆盖，保证可重复执行
      local rf
      for rf in "$repod"/*.repo; do
        [ -e "$rf" ] || continue
        [ "$(basename "$rf")" = "$repo" ] && continue
        mv -n "$rf" "$repod/bk/" 2>/dev/null || true
      done
      cat > "$repod/$repo" <<EOF
[EL]
name=Linux 7.x DVD
baseurl=file://$ISO_MOUNT
gpgcheck=0
enabled=1
EOF
      ok "已生成本地源 $repod/$repo（file://$ISO_MOUNT），原 repo 备份到 bk/"
    fi
  else
    warn "YUM_REPO=none，跳过光盘源配置，使用系统现有 yum 源"
  fi

  if have yum; then
    log "安装依赖包（共 ${#GP_PACKAGES[@]} 个，与原培训脚本一致）"
    if yum -y install "${GP_PACKAGES[@]}" >/dev/null 2>&1; then
      ok "依赖包整组安装成功"
    else
      warn "整组安装有失败，改为逐包安装以跳过缺失包（如 EL7 的 e4fsprogs）"
      local p
      for p in "${GP_PACKAGES[@]}"; do
        if yum -y install "$p" >/dev/null 2>&1; then ok "  已安装 $p"; else warn "  包不可用/安装失败：$p"; fi
      done
    fi
  else warn "无 yum，跳过依赖安装"; fi
}

# =============================================================================
# 汇总与重启
# =============================================================================
finish() {
  printf '\n%s\n' "================================================================"
  if [ "${#FAILED[@]}" -eq 0 ]; then
    ok "全部 OS 配置步骤已完成（可能有 WARN 告警，不影响主流程）。"
  else
    err "存在 ${#FAILED[@]} 个失败项："
    local i
    for i in "${FAILED[@]}"; do printf '         - %s\n' "$i"; done
  fi
  _log "详细日志：$LOG_FILE"
  _log "提示：内核/GRUB(NUMA、THP)、limits 等需【重启】后完全生效。"
  if [ "$REBOOT" = "yes" ]; then
    _log "REBOOT=yes，10 秒后重启（Ctrl+C 取消）..."
    sleep 10; shutdown -r now
  else
    _log "本次未自动重启；确认无误后手动执行：reboot（或用 REBOOT=yes 重跑本脚本）"
  fi
  printf '%s\n' "================================================================"
  [ "${#FAILED[@]}" -eq 0 ]
}

main() {
  preflight
  setup_sysctl
  setup_limits
  setup_security
  setup_disk
  setup_readahead
  setup_scheduler
  setup_grub
  setup_removeipc
  setup_yum
  finish
}

# 同时输出到屏幕与日志
main "$@" 2>&1 | tee -a "$LOG_FILE"
exit "${PIPESTATUS[0]}"
